<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxdhxyg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxdhxyg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxdhxyg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxdhxyg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxdhxyg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sxdhxyg',
    'container.build_id' => '229c4c03',
    'container.build_time' => 1658586964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxdhxyg');
